# Generated by Django 2.1.2 on 2019-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='new_field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='add_field',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='new_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
