
version: 2
jobs:
  build:
    docker:

      - image: circleci/python:3.6.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          command : |
              pip install virtualenv
              pip install --upgrade pip --user
      - run:
          name: create virtual environment
          command: virtualenv myvirtualenv --python=python3
      - run:
          name: activate virtual environment
          command: source /home/circleci/repo/myvirtualenv/bin/activate

      - run:
          name : install dependencies
          command:
            pip install -r requirements.txt

      - save_cache:
          paths:
            - /home/circleci/repo/myvirtualenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
